# Actual parameter values
diagnostic_msgs/KeyValue[] values

# Separate container for parameter types
diagnostic_msgs/KeyValue[] types

# Entry conditions
diagnostic_msgs/KeyValue[] entry_conds

# Exit (end, goals) conditions
diagnostic_msgs/KeyValue[] end_conds
 
# Rules for the action
diagnostic_msgs/KeyValue[] rules

# Performance criteria placed on the action
diagnostic_msgs/KeyValue[] criteria

# Deadline for completion
time deadline
